name: organizing_managing_student_projects
description: Приложение для управления учебными проектами
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2  # Flutter 3.22 / Dart 3.7+

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.5
  table_calendar: ^3.1.1

  # Backend
  supabase_flutter: ^2.9.1

  # Env variables
  flutter_dotenv: ^5.0.2

  # Utils
  uuid: ^4.5.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.0

  # Notifications
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4

  # PDF generation
  pdf: ^3.11.3
  printing: ^5.14.2

  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0

  device_calendar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/lang/
